// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azaqhsxlsqrvltcsmgve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6amZvZnVmdnJ0emhta2lzbXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDk2MjAsImV4cCI6MjA3MDc4NTYyMH0.0xT7PBdqMEHWo4h935Xe2CnCkIb3uE9MBRqdZGN9tsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});